### ISSUE TITLE
How about we do it using the nextjs?

### ISSUE THREAD

**Issue by Syammed2429** [krowter/area-51#2]
How about we do it using the nextJS and Tailwind with the shadcn

**Comment by krowter** [comment]
I'm cool with Tailwind/Shadcn, but I don't think Next.js brings anything to the table--since this app focuses on client-side interaction and has only 1 page

**Comment by Syammed2429** [comment]
> I'm cool with Tailwind/Shadcn, but I don't think Next.js brings anything to the table--since this app focuses on client-side interaction and has only 1 page

Yeah it do make sense then just need to do some styling for awesome interaction
